export { default as CommentAnchorBadge } from "./comment-anchor-badge.svelte";
export { default as CommentInspector } from "./comment-inspector.svelte";
export { default as CommentResourceLayer } from "./comment-resource-layer.svelte";
export { default as DefaultWebChatComposer } from "./default-composer.svelte";
export { default as MessageSourcePopup } from "./message-source-popup.svelte";
export { resolveMessageIdentityKey, toWebChatMessage, toWebChatMessages } from "./message-utils";
export {
  attachmentToResourceReference,
  buildCommentResourceSourceUri,
  commentResourceToReference,
  createCommentResourcePayload,
  formatAssetResourceDefinition,
  formatCommentResourceDefinition,
  mergeResourceReferences,
  normalizeCommentResourcePayload,
  normalizeResourceReferenceQuery,
  parseAssetResourceDefinition,
  parseCommentFootnoteDefinition,
  pendingAssetToResourceReference,
  resolveMessageResourceReferences,
  resourceReferenceMatchesQuery,
  serializeMessageSourceMarkdown,
} from "./resource-contract";
export type {
  WebChatActorPresentation,
  WebChatActorResolveInput,
  WebChatChannel,
  WebChatCommentDraftRequest,
  WebChatCommentResourceAnchor,
  WebChatCommentResourcePayload,
  WebChatComposerCapabilities,
  WebChatComposerCommandSuggestion,
  WebChatComposerCompletionContext,
  WebChatComposerCompletionDetection,
  WebChatComposerCompletionItem,
  WebChatComposerCompletionProvider,
  WebChatComposerCompletionTrigger,
  WebChatComposerHelpItem,
  WebChatComposerMentionSuggestion,
  WebChatComposerRenderProps,
  WebChatComposerSubmitPayload,
  WebChatComposerTextInsertion,
  WebChatConnectionState,
  WebChatCursor,
  WebChatMessage,
  WebChatMessageAction,
  WebChatMessageInput,
  WebChatMessageReadActor,
  WebChatMessageReadProgress,
  WebChatMessageReference,
  WebChatMessageRenderInput,
  WebChatNotice,
  WebChatResourceReference,
  WebChatResourceReferenceKind,
  WebChatRootProps,
  WebChatSocketFactory,
  WebChatSocketLike,
  WebChatTransportMessage,
  WebChatViewHostProps,
  WebChatVisibleMessageFact,
} from "./types";
export { default as WebChatView, default as WebChatViewHost } from "./web-chat-view-host.svelte";
