export const CLI_SHELL_HELP_PANEL_LINES = [
  "cli-shell help",
  "",
  "Status bar:",
  "  Click managed:on/off, Help, or Chat in the bottom bar.",
  "  The highlighted item shows the current cli-shell surface.",
  "  In cover Chat, tmux popup owns mouse focus; use the Chat titlebar or keyboard.",
  "",
  "Actions:",
  "  managed toggles cli-shell hosting attention for the selected Avatar.",
  "  Help   opens this panel.",
  "  Chat   toggles the MessageRoom. It starts open as the right dock by default.",
  "  Hidden expert keys still provide Dock, Mouse, Shell, and Refresh.",
  "",
  "How to press a tmux shortcut:",
  "  Press Ctrl+b, release both keys, then press the next key.",
  "  Example: Ctrl+b, then c toggles Chat.",
  "",
  "Keyboard:",
  "  Ctrl+b, then c  toggle Chat",
  "  Ctrl+b, then C  open persistent Chat dock",
  "  Ctrl+b, then m  toggle Mouse",
  "  Ctrl+b, then s  focus shell pane",
  "  Ctrl+b, then r  refresh status bar",
  "  Ctrl+b, then ?  show this help",
  "  Ctrl+b, then [  enter copy-mode for page scroll/search/copy",
  "",
  "Copy-mode:",
  "  PageUp/PageDown or arrow keys scroll",
  "  q exits copy-mode",
  "",
  "Help panel:",
  "  Esc, q, or Ctrl+Q closes this panel.",
];

export const CLI_SHELL_HELP_PANEL_TEXT = CLI_SHELL_HELP_PANEL_LINES.join("\n");
