import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterAll, describe, expect, test } from "bun:test";
import { quoteShellArg, renderTmuxStatusBar, TmuxClient } from "@agenter/tmux-client";

import {
  buildCliShellStatusBarDefinition,
  buildCliShellStatusBarOptionCommands,
  CLI_SHELL_TMUX_STATUS_LEFT_LENGTH,
  CLI_SHELL_TMUX_STATUS_MIN_COLUMNS,
  CLI_SHELL_TMUX_STATUS_RIGHT_LENGTH,
} from "../src/tmux-statusbar";

describe("Feature: cli-shell status bar declaration", () => {
  const tempDirs: string[] = [];

  afterAll(() => {
    for (const dir of tempDirs) {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  test("Scenario: Given cli-shell declares status buttons When rendering through tmux-client Then Help and Chat are app buttons without host shell glue", () => {
    const rendered = renderTmuxStatusBar(
      buildCliShellStatusBarDefinition({
        shellName: "shell-5",
        avatarNickname: "bangeel",
      }),
    );

    expect(rendered.buttonIds).toEqual(["managed", "help", "chat"]);
    expect(rendered.statusLeft).toContain("cli-shell");
    expect(rendered.statusLeft).toContain("shell-5");
    expect(rendered.statusLeft).toContain("@bangeel");
    expect(rendered.statusLeft).toContain("range=user|managed");
    expect(rendered.statusLeft.indexOf("range=user|managed")).toBeLessThan(
      rendered.statusLeft.indexOf("@agenter_cli_shell_heartbeat_status"),
    );
    expect(rendered.statusRight).toContain("range=user|help");
    expect(rendered.statusRight).toContain("range=user|chat");
    expect(rendered.statusRight).not.toContain("tmux-action");
    expect(rendered.statusRight).not.toContain("run-shell");
  });

  test("Scenario: Given cli-shell statusbar is installed When commands are built Then status options are generated by the generic tmux library", () => {
    const commands = buildCliShellStatusBarOptionCommands({
      shellName: "shell-5",
      avatarNickname: "bangeel",
    });

    expect(commands.map((command) => command.args[3])).toEqual([
      "status",
      "status-position",
      "status-style",
      "status-left-style",
      "status-right-style",
      "status-left",
      "status-left-length",
      "status-right-length",
      "status-right",
      "window-status-format",
      "window-status-current-format",
    ]);
    expect(commands.every((command) => command.args[0] === "set-option")).toBe(true);
    expect(commands.every((command) => command.args[1] === "-t" && command.args[2] === "shell-5")).toBe(true);
    expect(commands.find((command) => command.args.includes("status-left-length"))?.args.at(-1)).toBe(
      String(CLI_SHELL_TMUX_STATUS_LEFT_LENGTH),
    );
    expect(commands.find((command) => command.args.includes("status-right-length"))?.args.at(-1)).toBe(
      String(CLI_SHELL_TMUX_STATUS_RIGHT_LENGTH),
    );
    expect(CLI_SHELL_TMUX_STATUS_LEFT_LENGTH + CLI_SHELL_TMUX_STATUS_RIGHT_LENGTH).toBeLessThanOrEqual(
      CLI_SHELL_TMUX_STATUS_MIN_COLUMNS - 2,
    );
  });

  test(
    "Scenario: Given the real cli-shell status bar runs in tmux When the user clicks bottom buttons Then managed Help and Chat ranges stay isolated",
    async () => {
      const tmuxPath = Bun.which("tmux");
      const expectPath = Bun.which("expect");
      if (!tmuxPath || !expectPath) {
        return;
      }
      const cwd = mkdtempSync(join(tmpdir(), "cli-shell-status-"));
      tempDirs.push(cwd);
      const outputPath = join(cwd, "ranges.txt");
      const socketName = `agenter-cli-shell-status-test-${Date.now()}-${Math.random().toString(16).slice(2)}`;
      const sessionName = "cli-shell-status-test";
      const client = new TmuxClient({ executable: tmuxPath, socketName });

      try {
        await client.newSession({ sessionName, detached: true, cwd, command: ["sh", "-lc", "sleep 60"] });
        await client.setOption({ target: sessionName, name: "mouse", value: "on" });
        await client.setOption({ target: sessionName, name: "@agenter_cli_shell_active_action", value: "shell" });
        await client.setOption({ target: sessionName, name: "@agenter_cli_shell_managed", value: "off" });
        await client.setOption({
          target: sessionName,
          name: "@agenter_cli_shell_heartbeat_status",
          value: "heartbeat heartbeat heartbeat heartbeat heartbeat",
        });
        for (const command of buildCliShellStatusBarOptionCommands({
          shellName: sessionName,
          avatarNickname: "bangeel",
        })) {
          await client.exec(command.args);
        }
        await client.exec([
          "bind-key",
          "-T",
          "root",
          "MouseDown1Status",
          "run-shell",
          `printf '%s:%s:%s\\n' '#{mouse_x}' '#{mouse_y}' '#{mouse_status_range}' >> ${quoteShellArg(outputPath)}`,
        ]);

        await runExpectMouseClicks({
          expectPath,
          tmuxPath,
          socketName,
          sessionName,
          columns: CLI_SHELL_TMUX_STATUS_MIN_COLUMNS,
          rows: 24,
          // These coordinates come from the real 80-column cli-shell status layout:
          // managed lives near the end of status-left; Help/Chat live in status-right.
          xCoordinates: [48, 51, 66, 69, 72, 75, 78],
        });

        const ranges = await waitForStatusRanges(outputPath, ["managed", "help", "chat"]);

        expect(ranges.includes("managed")).toBe(true);
        expect(ranges.includes("help")).toBe(true);
        expect(ranges.includes("chat")).toBe(true);
      } finally {
        await client.killSession(sessionName).catch(() => undefined);
      }
    },
    10_000,
  );
});

const runExpectMouseClicks = async (input: {
  expectPath: string;
  tmuxPath: string;
  socketName: string;
  sessionName: string;
  columns: number;
  rows: number;
  xCoordinates: readonly number[];
}): Promise<void> => {
  const clickScript = input.xCoordinates
    .map((x) => `send "\\033\\[<0;${x};${input.rows}M"; after 20; send "\\033\\[<0;${x};${input.rows}m"; after 40`)
    .join("; ");
  const script = [
    "set timeout 4",
    `spawn -noecho env TERM=xterm-256color ${input.tmuxPath} -L ${input.socketName} attach -t ${input.sessionName}`,
    `stty rows ${input.rows} columns ${input.columns}`,
    "after 400",
    clickScript,
    "after 400",
    'send "\\002d"',
    "expect eof",
  ].join("; ");
  const proc = Bun.spawn([input.expectPath, "-c", script], {
    stdout: "pipe",
    stderr: "pipe",
  });
  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  if (exitCode !== 0) {
    throw new Error(`expect tmux mouse probe failed with ${exitCode}\nstdout:\n${stdout}\nstderr:\n${stderr}`);
  }
};

const readStatusRangeOutput = (path: string): string[] => {
  try {
    return readFileSync(path, "utf8")
      .split("\n")
      .map((line) => line.trim().split(":").at(-1)?.trim() ?? "")
      .filter(Boolean);
  } catch {
    return [];
  }
};

const waitForStatusRanges = async (path: string, expected: readonly string[]): Promise<string[]> => {
  const deadline = Date.now() + 2_000;
  let ranges: string[] = [];
  do {
    ranges = readStatusRangeOutput(path);
    if (expected.every((range) => ranges.includes(range))) {
      return ranges;
    }
    await delay(50);
  } while (Date.now() < deadline);
  return ranges;
};

const delay = async (ms: number): Promise<void> => {
  await new Promise<void>((resolve) => setTimeout(resolve, ms));
};
