export type {
  Cell,
  CursorState,
  KeyDescriptor,
  RGB,
  ScrollbackState,
  Terminal,
  TerminalBackend,
  TerminalCapabilities,
  TerminalCreateOptions,
  TerminalMode,
  TerminalOptions,
  TerminalReadable,
  UnderlineStyle,
} from "@termless/core";
