export { AgenticTerminal } from "./agentic-terminal";
export type {
  TerminalTransportClientMessage,
  TerminalTransportServerMessage,
} from "@agenter/terminal-transport-protocol";
export { resolveDefaultInteractiveShellCommand } from "./default-shell-command";
export {
  ManagedTerminal,
  type ManagedTerminalConfig,
  type ManagedTerminalLifecycleEvent,
  type ManagedTerminalSnapshot,
} from "./managed-terminal";
export { keyToSequence, parseMixedInput, runMixedInput } from "./input-parser";
export { readTerminalOutput, readTerminalOutputLines, streamTerminalOutput } from "./output-reader";
export {
  compactRenderForPersistence,
  renderSemanticBuffer,
  renderStructuredBuffer,
  serializeStructuredLinesForLog,
  stripHtmlTags,
} from "./renderer";
export { XtermBridge } from "./xterm-bridge";
export {
  TerminalControlPlane,
} from "./terminal-control-plane";
export {
  DEFAULT_TERMINAL_BACKEND,
  DEFAULT_TERMINAL_CURSOR,
  DEFAULT_TERMINAL_FONT,
  DEFAULT_TERMINAL_RENDERER_PREFERENCE,
  DEFAULT_TERMINAL_THEME,
  TERMINAL_BACKEND_KINDS,
} from "./terminal-control-plane.types";
export type {
  TerminalAccessProjection,
  TerminalActorId,
  TerminalAdminCandidateRecord,
  TerminalAwaitInput,
  TerminalAwaitMatchEvidence,
  TerminalAwaitMatchOptions,
  TerminalAwaitOutcome,
  TerminalAwaitResult,
  TerminalAwaitUntil,
  TerminalAwaitViewOptions,
  TerminalAwaitWaitOptions,
  TerminalAutomationInputMode,
  TerminalBackendKind,
  TerminalApprovalRequestRecord,
  TerminalApprovalStatus,
  TerminalAcceptSeatInput,
  TerminalControlPlaneConfig,
  TerminalControlPlaneConfigPatch,
  TerminalControlPlaneEntry,
  TerminalConfigMutationResult,
  TerminalConfigSeatInput,
  TerminalConfigView,
  TerminalCreateInput,
  TerminalEventKind,
  TerminalEventPayload,
  TerminalEventRecord,
  TerminalFocusOp,
  TerminalFontProfile,
  TerminalGrantWriteLeaseInput,
  TerminalGrantRecord,
  TerminalGrantRole,
  TerminalInvitationRecord,
  TerminalInviteSeatInput,
  TerminalIssueGrantInput,
  TerminalInputInput,
  TerminalIssuedGrant,
  TerminalManagedSeatClass,
  TerminalManagedSeatPayload,
  TerminalPatchInput,
  TerminalProcessProfile,
  TerminalReadCursorRecord,
  TerminalReadMode,
  TerminalReadProjection,
  TerminalReadResult,
  TerminalRecord,
  TerminalRevokeWriteLeaseInput,
  TerminalRendererPreference,
  TerminalResolvedRenderer,
  TerminalReverseCursor,
  TerminalReversePage,
  TerminalSeatProjection,
  TerminalShortcutMap,
  TerminalCursorStyle,
  TerminalThemeName,
  TerminalTransportConfig,
  TerminalTransportEndpoint,
  TerminalRevokeSeatInput,
  TerminalWriteInput,
  TerminalWriteLeaseRecord,
  TerminalWriteResult,
} from "./terminal-control-plane.types";
export type {
  TerminalLifecycleState,
  TerminalLifecycleTransition,
  TerminalObservedIdentity,
  TerminalProcessPhase,
  TerminalStopReason,
} from "./terminal-runtime-truth";
export type {
  PageMeta,
  RenderResult,
  RichLine,
  RichSpan,
  StructuredRenderResult,
  TerminalColorMode,
  TerminalColorOption,
  TerminalDirtyMarkResult,
  TerminalDirtySliceOptions,
  TerminalDirtySliceResult,
  TerminalGitLogMode,
  TerminalGitLogOption,
  TerminalLogStyle,
  TerminalLogStyleOption,
  TerminalPendingInputMode,
  TerminalPendingInputOptions,
  TerminalPendingInputResult,
  TerminalProfile,
  TerminalStatus,
  TerminalStructuredSnapshot,
} from "./types";
