export { AgenticTerminal } from "./agentic-terminal";
export {
  ManagedTerminal,
  type ManagedTerminalConfig,
  type ManagedTerminalSnapshot,
} from "./managed-terminal";
export { keyToSequence, parseMixedInput, runMixedInput } from "./input-parser";
export { readTerminalOutput, readTerminalOutputLines, streamTerminalOutput } from "./output-reader";
export {
  compactRenderForPersistence,
  renderSemanticBuffer,
  renderStructuredBuffer,
  serializeStructuredLinesForLog,
  stripHtmlTags,
} from "./renderer";
export {
  TerminalControlPlane,
} from "./terminal-control-plane";
export type {
  TerminalAccessProjection,
  TerminalActorId,
  TerminalAdminCandidateRecord,
  TerminalApprovalRequestRecord,
  TerminalApprovalStatus,
  TerminalControlPlaneConfig,
  TerminalControlPlaneConfigPatch,
  TerminalControlPlaneEntry,
  TerminalCreateInput,
  TerminalEventKind,
  TerminalEventPayload,
  TerminalEventRecord,
  TerminalFocusOp,
  TerminalGrantRecord,
  TerminalGrantRole,
  TerminalIssueGrantInput,
  TerminalIssuedGrant,
  TerminalPatchInput,
  TerminalProcessProfile,
  TerminalReadMode,
  TerminalReadProjection,
  TerminalReadResult,
  TerminalRecord,
  TerminalRendererEngine,
  TerminalReverseCursor,
  TerminalReversePage,
  TerminalSeatProjection,
  TerminalShortcutMap,
  TerminalTransportClientMessage,
  TerminalTransportConfig,
  TerminalTransportEndpoint,
  TerminalTransportServerMessage,
  TerminalWriteInput,
  TerminalWriteLeaseRecord,
  TerminalWriteResult,
} from "./terminal-control-plane.types";
export type {
  PageMeta,
  RenderResult,
  RichLine,
  RichSpan,
  StructuredRenderResult,
  TerminalColorMode,
  TerminalColorOption,
  TerminalDirtyMarkResult,
  TerminalDirtySliceOptions,
  TerminalDirtySliceResult,
  TerminalGitLogMode,
  TerminalGitLogOption,
  TerminalLogStyle,
  TerminalLogStyleOption,
  TerminalPendingInputOptions,
  TerminalPendingInputResult,
  TerminalProfile,
  TerminalStatus,
  TerminalStructuredSnapshot,
} from "./types";
