export { AgenticTerminal } from "./agentic-terminal";
export {
  ManagedTerminal,
  type ManagedTerminalConfig,
  type ManagedTerminalLifecycleEvent,
  type ManagedTerminalSnapshot,
} from "./managed-terminal";
export { keyToSequence, parseMixedInput, runMixedInput } from "./input-parser";
export { readTerminalOutput, readTerminalOutputLines, streamTerminalOutput } from "./output-reader";
export {
  compactRenderForPersistence,
  renderSemanticBuffer,
  renderStructuredBuffer,
  serializeStructuredLinesForLog,
  stripHtmlTags,
} from "./renderer";
export {
  TerminalControlPlane,
} from "./terminal-control-plane";
export type {
  TerminalAccessProjection,
  TerminalActorId,
  TerminalAdminCandidateRecord,
  TerminalAwaitInput,
  TerminalAwaitMatchEvidence,
  TerminalAwaitMatchOptions,
  TerminalAwaitOutcome,
  TerminalAwaitResult,
  TerminalAwaitUntil,
  TerminalAwaitViewOptions,
  TerminalAwaitWaitOptions,
  TerminalAutomationInputMode,
  TerminalApprovalRequestRecord,
  TerminalApprovalStatus,
  TerminalControlPlaneConfig,
  TerminalControlPlaneConfigPatch,
  TerminalControlPlaneEntry,
  TerminalConfigMutationResult,
  TerminalConfigView,
  TerminalCreateInput,
  TerminalEventKind,
  TerminalEventPayload,
  TerminalEventRecord,
  TerminalFocusOp,
  TerminalGrantRecord,
  TerminalGrantRole,
  TerminalIssueGrantInput,
  TerminalInputInput,
  TerminalIssuedGrant,
  TerminalPatchInput,
  TerminalProcessProfile,
  TerminalReadCursorRecord,
  TerminalReadMode,
  TerminalReadProjection,
  TerminalReadResult,
  TerminalRecord,
  TerminalRendererEngine,
  TerminalReverseCursor,
  TerminalReversePage,
  TerminalSeatProjection,
  TerminalShortcutMap,
  TerminalTransportClientMessage,
  TerminalTransportConfig,
  TerminalTransportEndpoint,
  TerminalTransportServerMessage,
  TerminalWriteInput,
  TerminalWriteLeaseRecord,
  TerminalWriteResult,
} from "./terminal-control-plane.types";
export type {
  TerminalLifecycleState,
  TerminalLifecycleTransition,
  TerminalObservedIdentity,
  TerminalProcessPhase,
  TerminalStopReason,
} from "./terminal-runtime-truth";
export type {
  PageMeta,
  RenderResult,
  RichLine,
  RichSpan,
  StructuredRenderResult,
  TerminalColorMode,
  TerminalColorOption,
  TerminalDirtyMarkResult,
  TerminalDirtySliceOptions,
  TerminalDirtySliceResult,
  TerminalGitLogMode,
  TerminalGitLogOption,
  TerminalLogStyle,
  TerminalLogStyleOption,
  TerminalPendingInputMode,
  TerminalPendingInputOptions,
  TerminalPendingInputResult,
  TerminalProfile,
  TerminalStatus,
  TerminalStructuredSnapshot,
} from "./types";
