<script lang="ts">
	import KeyRoundIcon from '@lucide/svelte/icons/key-round';
	import ShieldCheckIcon from '@lucide/svelte/icons/shield-check';

	import ScrollView from '$lib/components/scroll-view.svelte';
	import PasswordInput from '$lib/components/ui/password-input.svelte';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Dialog from '$lib/components/ui/dialog/index.js';
	import type { AuthServiceInfoOutput } from '@agenter/client-sdk';

	let {
		open = $bindable(false),
		authService,
		authStatus,
		privateKeyDraft = $bindable(''),
		canRevealManagedKey,
		managedKeyBusy,
		onRevealManagedKey,
		onAuthenticate,
		onDismiss,
	}: {
		open?: boolean;
		authService: AuthServiceInfoOutput | null;
		authStatus: string;
		privateKeyDraft?: string;
		canRevealManagedKey: boolean;
		managedKeyBusy: boolean;
		onRevealManagedKey: () => Promise<void> | void;
		onAuthenticate: () => Promise<void> | void;
		onDismiss: () => void;
	} = $props();

	const fallbackKeyPath = '~/.agenter/profile-service/root-auth.key';
</script>

<Dialog.Root bind:open>
	<Dialog.Content class="grid max-h-[calc(100dvh-2rem)] grid-rows-[auto_minmax(0,1fr)_auto] gap-0 p-0 sm:max-w-2xl">
		<Dialog.Header class="border-b p-6">
			<Dialog.Title>Bind superadmin key</Dialog.Title>
			<Dialog.Description>
				The root key is generated by profile-service on first start. Authenticate once here so the WebUI has an explicit
				superadmin seat instead of silently running unauthenticated.
			</Dialog.Description>
		</Dialog.Header>

		<ScrollView class="min-h-0" contentClass="space-y-4 p-6">
			<div class="flex flex-wrap gap-2 text-xs text-muted-foreground">
				<div class="rounded-full border bg-muted px-3 py-1">{authService?.authMode ?? 'wallet_challenge_jwt'}</div>
				<div class="rounded-full border bg-muted px-3 py-1">{authService?.rootAuthId ?? 'root auth unavailable'}</div>
				<div class="rounded-full border bg-muted px-3 py-1">
					{authService?.rootAuthBootstrapMode ?? 'managed_local'}
				</div>
				<div class="rounded-full border bg-muted px-3 py-1">
					root key: {authService?.rootAuthKeyPath ?? fallbackKeyPath}
				</div>
			</div>

			<div class="rounded-2xl border bg-muted/50 p-4 text-sm text-muted-foreground">
				<div class="mb-2 flex items-center gap-2 font-medium text-foreground">
					<ShieldCheckIcon class="size-4" />
					<span>What happened</span>
				</div>
				<p>
					profile-service has already prepared the superadmin private key. This dialog makes that fact visible, shows
					where the key lives, and lets you turn it into the short-lived auth token used by the WebUI.
				</p>
			</div>

			{#if canRevealManagedKey}
				<div class="rounded-2xl border border-primary/20 bg-primary/5 p-4 text-sm text-muted-foreground">
					<div class="flex flex-wrap items-center justify-between gap-3">
						<p class="max-w-prose">
							Use the backend-managed root key to prefill this field. The key is only revealed when you click the
							button below.
						</p>
						<Button variant="secondary" onclick={() => void onRevealManagedKey()} disabled={managedKeyBusy}>
							<KeyRoundIcon class="size-4" />
							{managedKeyBusy ? 'Loading key…' : 'Use backend-managed key'}
						</Button>
					</div>
				</div>
			{/if}

			<label class="grid gap-2 text-sm font-medium text-foreground">
				<span>Root private key</span>
				<PasswordInput bind:value={privateKeyDraft} placeholder="0x-prefixed private key" />
			</label>

			<p class="text-xs text-muted-foreground">
				The private key is only used locally to sign one challenge. The browser stores the short-lived auth token, not
				the private key.
			</p>

			<div class="rounded-2xl border bg-muted/40 px-4 py-3 text-sm text-muted-foreground">{authStatus}</div>
		</ScrollView>

		<Dialog.Footer class="border-t p-6">
			<Button variant="ghost" onclick={onDismiss}>Later</Button>
			<Button onclick={() => void onAuthenticate()} disabled={!privateKeyDraft.trim()}>
				<KeyRoundIcon class="size-4" />
				Sign challenge
			</Button>
		</Dialog.Footer>
	</Dialog.Content>
</Dialog.Root>
