import type { AuthServiceInfoOutput } from "@agenter/client-sdk";
import { KeyRound, ShieldCheck } from "lucide-react";

import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Dialog } from "../../components/ui/dialog";
import { PasswordInput } from "../../components/ui/password-input";

interface SuperadminOnboardingDialogProps {
  open: boolean;
  authService: AuthServiceInfoOutput | null;
  authStatus: string;
  privateKeyDraft: string;
  canRevealManagedKey: boolean;
  managedKeyBusy: boolean;
  onPrivateKeyDraftChange: (value: string) => void;
  onRevealManagedKey: () => Promise<void> | void;
  onAuthenticate: () => Promise<void> | void;
  onDismiss: () => void;
}

const fallbackKeyPath = "~/.agenter/profile-service/root-auth.key";

export const SuperadminOnboardingDialog = ({
  open,
  authService,
  authStatus,
  privateKeyDraft,
  canRevealManagedKey,
  managedKeyBusy,
  onPrivateKeyDraftChange,
  onRevealManagedKey,
  onAuthenticate,
  onDismiss,
}: SuperadminOnboardingDialogProps) => {
  return (
    <Dialog
      open={open}
      title="Bind superadmin key"
      description="The root key is generated by profile-service on first start. Authenticate once here so the WebUI has an explicit superadmin seat instead of silently running unauthenticated."
      onClose={onDismiss}
      footer={
        <>
          <Button type="button" variant="ghost" onClick={onDismiss}>
            Later
          </Button>
          <Button type="button" onClick={() => void onAuthenticate()} disabled={!privateKeyDraft.trim()}>
            <KeyRound className="h-4 w-4" />
            Sign challenge
          </Button>
        </>
      }
    >
      <div className="space-y-4">
        <div className="flex flex-wrap gap-2 text-xs text-slate-600">
          <Badge variant="secondary">{authService?.authMode ?? "wallet_challenge_jwt"}</Badge>
          <Badge variant="secondary">{authService?.rootAuthId ?? "root auth unavailable"}</Badge>
          <Badge variant="secondary">{authService?.rootAuthBootstrapMode ?? "managed_local"}</Badge>
          <Badge variant="secondary">
            root key: {authService?.rootAuthKeyPath ?? fallbackKeyPath}
          </Badge>
        </div>

        <div className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-sm text-slate-700">
          <div className="mb-2 flex items-center gap-2 text-slate-900">
            <ShieldCheck className="h-4 w-4" />
            <span className="font-medium">What happened</span>
          </div>
          <p>
            profile-service has already prepared the superadmin private key. This dialog makes that fact visible, shows
            where the key lives, and lets you turn it into the short-lived auth token used by the WebUI.
          </p>
        </div>

        {canRevealManagedKey ? (
          <div className="rounded-xl border border-dashed border-teal-300 bg-teal-50/70 px-3 py-3 text-sm text-slate-700">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <p className="max-w-prose">
                Use the backend-managed root key to prefill this field. The key is only revealed when you click the
                button below.
              </p>
              <Button type="button" variant="secondary" onClick={() => void onRevealManagedKey()} disabled={managedKeyBusy}>
                <KeyRound className="h-4 w-4" />
                {managedKeyBusy ? "Loading key..." : "Use backend-managed key"}
              </Button>
            </div>
          </div>
        ) : null}

        <label className="grid gap-2">
          <span className="text-sm font-medium text-slate-900">Root private key</span>
          <PasswordInput
            value={privateKeyDraft}
            onChange={(event) => onPrivateKeyDraftChange(event.target.value)}
            placeholder="0x-prefixed private key"
            toggleLabel={{ show: "Show private key", hide: "Hide private key" }}
          />
        </label>

        <p className="text-xs text-slate-500">
          The private key is only used locally to sign one challenge. The browser stores the short-lived auth token, not
          the private key.
        </p>

        <div className="rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm text-slate-700">{authStatus}</div>
      </div>
    </Dialog>
  );
};
